name: pfephoboapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

# file_picker déclenche des avertissements sur desktop
# mais fonctionne sans problème sur Android/iOS
dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_dynamic_links: 6.1.5 # (discontinued)
  shared_preferences: ^2.2.2
  firebase_storage: ^12.4.5
  supabase_flutter: ^1.10.25 # ou la dernière version stable
  image_picker: ^1.0.4
  file_picker: ^10.1.2 # version compatible et stable
  path: ^1.9.0
  path_provider: ^2.0.8

  # Autres plugins utiles
  google_sign_in: ^6.2.1
  video_player: ^2.8.6
  chewie: ^1.6.0
  youtube_player_flutter: ^9.1.1  # Version stable sans conflit
  permission_handler: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300