name: pfephoboapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1

  # Internationalisation
  intl: ^0.18.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  shared_preferences: ^2.2.2
  firebase_dynamic_links: ^6.1.5 # dernière version compatible avec firebase_core v3

  # Supabase
  supabase_flutter: ^1.10.25 # compatible avec sign_in_with_apple ^5.0.0 (contourné ci-dessous)

  # Authentification
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  # Fichiers et médias
  file_picker: ^10.1.9
  image_picker: ^1.0.4
  video_player: ^2.8.6
  chewie: ^1.6.0
  youtube_player_flutter: ^9.1.1

  # Permissions
  permission_handler: ^11.4.0

  # Fichiers
  path: ^1.9.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  sign_in_with_apple: ^6.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
